classdef ParamConst
   properties (Constant)
        pavWidth=0;
        pavHeight=1;
        pavLevel=2;
        pavSpan=3;
        pavEpsilon=4;
        pavDistance=5;
        pavPathTemp=6;
        pavEnvTemp=7;
        pavAbsorption=8;
        pavDataVersion=9;
        pavZoom=10;
        pavKamera=11;
        pavKameraSNr=12;
        pavLens=13;
        pavPixelFormat=14;
        pavTransmission=15;
        pavLambda=16;
        pavDeltaLambda=17;
        pavMilliTime=18;
        pavTimeStamp=19;
        pavCalibMin=20;
        pavCalibMax=21;
        pavTriggered=22;
        pavIntegtime=23;
        pavHFOV=24;
        pavVFOV=25;
        pavSmooth=26;
        pavCamTemp=27;
        pavSensorTemp=28;
        pavDigVals=29;
        pavAD1=30;
        pavAD2=31;
        pavAD3=32;
        pavAD4=33;
        pavAD5=34;
        pavHeightWithHdr=35;
   end
end
